### model
model_name_or_path: Qwen/Qwen3-0.6B
trust_remote_code: true
flash_attn: fa2

### method
stage: distill1
do_train: true
finetuning_type: full


### dataset
dataset: gsm8kall,MATHall
template: qwen3_nothink
cutoff_len: 40000
max_samples: 40

### output
output_dir: saves/qwen3-0.6b/test
logging_steps: 1
save_steps: 3
plot_loss: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5e-7
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
resume_from_checkpoint: null
overwrite_output_dir: true

val_size: 0.05
eval_strategy: steps
eval_steps: 3
do_eval: true
per_device_eval_batch_size: 1

deepspeed: examples/deepspeed/ds_z2_offload_config.json

teacher_name: Qwen/Qwen3-4B-Instruct-2507 
select_type: random
train_alpha: 1